name: mandatory part
on: [push]
jobs:
  mandatory-part:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: tests
    steps:
    - uses: actions/checkout@v2
    - name: mandatory test
      run: bash run.sh m
