name: tripouille part
on: [push]
jobs:
  tripouille:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: srcs/gnlTester
    steps:
    - uses: actions/checkout@v2
    - name: tripouille tester
      run: make a